name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # 如果你的默认分支叫 master，把 main 改成 master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # 这里去掉了 cache: 'npm'，就不会再强制找锁文件了

      - name: Install dependencies and build
        run: |
          npm install --package-lock=false
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
